name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:  
          node-version: 14.X
      - run: npm install
      - run: npm run all
      - name: Zip Release
      - uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: fullmoon.zip
          path: ./dist
          directory: ./dist
      - name: Action Release
      - uses: yakuhzi/release-asset@v1.2.3
        with:
          file: fullmoon.zip
